config = {
    'AVERAGE_TRAFFIC_TRESHOLD': 10,
    'ERRORS_ALERT_INTERVAL': 10,
    'INPUT_LOG_FILE_PATH': '/var/log/access.log',
    'MAX_ERRORS_TRESHOLD': 10,
    'REFRESH_RATE': 1,
    'STATISTICS_INTERVAL': 10,
    'TRAFFIC_ALERT_TIME_WINDOW': 120,
    'TRAFFIC_ALERT_UPDATE_RATE': 10,
}
